jobs:
  build:
    docker:
      - image: node:latest
      - image: ehacke/firestore-emulator:latest
        name: firestore
        environment:
          - FIRESTORE_PROJECT_ID=project-test
          - FIRESTORE_LISTEN_ADDRESS=0.0.0.0:8080
        ports:
          - "8080:8080"
        command: "--no-store-on-disk --consistency=1.0"
      - image: redis:latest
        name: redis
        ports:
          - "6379:6379"
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: testing
          command: npm run test
      - run:
          name: coverage
          command: npx codecov
workflows:
  version: 2
  test-and-build:
    jobs:
      - build
